"""crear esquema inicial seguridad

Revision ID: 221f559e94f2
Revises: 
Create Date: 2026-05-13 05:39:55.180862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '221f559e94f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('calles_nodes',
    sa.Column('id_node', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id_node')
    )
    op.create_index('idx_calles_nodes_geom', 'calles_nodes', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('fuentes_datos',
    sa.Column('id_fuente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_fuente')
    )
    op.create_table('modelos_ia',
    sa.Column('id_modelo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=True),
    sa.Column('tipo_modelo', sa.String(length=80), nullable=False),
    sa.Column('proveedor', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_modelo')
    )
    op.create_table('municipios',
    sa.Column('id_municipio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.String(length=120), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', spatial_index=False,srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_municipio')
    )
    op.create_index('idx_municipios_geom', 'municipios', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('track_objetos',
    sa.Column('id_track', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.String(length=120), nullable=False),
    sa.Column('tipo_objeto', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('confianza_global', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('ultima_ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_track'),
    sa.UniqueConstraint('tracking_id')
    )
    op.create_index('idx_track_objetos_ultima_ubicacion', 'track_objetos', ['ultima_ubicacion'], unique=False, postgresql_using='gist')
    op.create_table('ejecuciones_modelo',
    sa.Column('id_ejecucion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metricas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelos_ia.id_modelo'], ),
    sa.PrimaryKeyConstraint('id_ejecucion')
    )
    op.create_table('puntos_turisticos',
    sa.Column('id_punto_turistico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_municipio', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=180), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False,srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], ),
    sa.PrimaryKeyConstraint('id_punto_turistico')
    )
    op.create_index('idx_puntos_turisticos_ubicacion', 'puntos_turisticos', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_table('zonas',
    sa.Column('id_zona', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_municipio', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=180), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('riesgo_base', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reputacion_base', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nivel_luz_base', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centro', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], ),
    sa.PrimaryKeyConstraint('id_zona')
    )
    op.create_index('idx_zonas_centro', 'zonas', ['centro'], unique=False, postgresql_using='gist')
    op.create_index('idx_zonas_geom', 'zonas', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('calles_edges',
    sa.Column('id_edge', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.BigInteger(), nullable=True),
    sa.Column('target', sa.BigInteger(), nullable=True),
    sa.Column('id_zona', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=180), nullable=True),
    sa.Column('tipo_via', sa.String(length=80), nullable=True),
    sa.Column('distancia_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('velocidad_estimada_kmh', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('riesgo_base', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('costo_base', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_zona'], ['zonas.id_zona'], ),
    sa.ForeignKeyConstraint(['source'], ['calles_nodes.id_node'], ),
    sa.ForeignKeyConstraint(['target'], ['calles_nodes.id_node'], ),
    sa.PrimaryKeyConstraint('id_edge')
    )
    op.create_index('idx_calles_edges_geom', 'calles_edges', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('camaras',
    sa.Column('id_camara', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_municipio', sa.Integer(), nullable=True),
    sa.Column('id_zona', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo_externo', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fuente', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False,srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('direccion_texto', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], ),
    sa.ForeignKeyConstraint(['id_zona'], ['zonas.id_zona'], ),
    sa.PrimaryKeyConstraint('id_camara')
    )
    op.create_index('idx_camaras_ubicacion', 'camaras', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_table('eventos_seguridad',
    sa.Column('id_evento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_zona', sa.Integer(), nullable=True),
    sa.Column('id_track', sa.BigInteger(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('severidad', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_track'], ['track_objetos.id_track'], ),
    sa.ForeignKeyConstraint(['id_zona'], ['zonas.id_zona'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_index('idx_eventos_seguridad_ubicacion', 'eventos_seguridad', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_table('factores_riesgo_zona',
    sa.Column('id_factor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_zona', sa.Integer(), nullable=False),
    sa.Column('id_fuente', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('reportes_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('luz_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reputacion_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hora_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('camaras_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('flujo_personas_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comportamiento_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('riesgo_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_fuente'], ['fuentes_datos.id_fuente'], ),
    sa.ForeignKeyConstraint(['id_zona'], ['zonas.id_zona'], ),
    sa.PrimaryKeyConstraint('id_factor')
    )
    op.create_table('historial_riesgo_zona',
    sa.Column('id_historial', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_zona', sa.Integer(), nullable=False),
    sa.Column('riesgo_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('desglose', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('algoritmo', sa.String(length=120), nullable=True),
    sa.Column('fecha_calculo', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_zona'], ['zonas.id_zona'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_table('reportes_seguridad',
    sa.Column('id_reporte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_zona', sa.Integer(), nullable=True),
    sa.Column('id_fuente', sa.Integer(), nullable=True),
    sa.Column('tipo_reporte', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('severidad', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_fuente'], ['fuentes_datos.id_fuente'], ),
    sa.ForeignKeyConstraint(['id_zona'], ['zonas.id_zona'], ),
    sa.PrimaryKeyConstraint('id_reporte')
    )
    op.create_index('idx_reportes_seguridad_ubicacion', 'reportes_seguridad', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_table('alertas_seguridad',
    sa.Column('id_alerta', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta', sa.String(length=80), nullable=False),
    sa.Column('prioridad', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('fecha_alerta', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_atencion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos_seguridad.id_evento'], ),
    sa.PrimaryKeyConstraint('id_alerta')
    )
    op.create_table('camara_cobertura',
    sa.Column('id_cobertura', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_camara', sa.Integer(), nullable=False),
    sa.Column('angulo', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('distancia_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_camara'], ['camaras.id_camara'], ),
    sa.PrimaryKeyConstraint('id_cobertura')
    )
    op.create_index('idx_camara_cobertura_geom', 'camara_cobertura', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('camara_estados',
    sa.Column('id_estado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_camara', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fps_actual', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('latencia_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.Column('fecha_estado', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_camara'], ['camaras.id_camara'], ),
    sa.PrimaryKeyConstraint('id_estado')
    )
    op.create_table('camara_streams',
    sa.Column('id_stream', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_camara', sa.Integer(), nullable=False),
    sa.Column('url_stream', sa.Text(), nullable=False),
    sa.Column('protocolo', sa.String(length=50), nullable=True),
    sa.Column('usuario', sa.String(length=120), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_camara'], ['camaras.id_camara'], ),
    sa.PrimaryKeyConstraint('id_stream')
    )
    op.create_table('detecciones_camara',
    sa.Column('id_deteccion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_camara', sa.Integer(), nullable=False),
    sa.Column('id_modelo', sa.Integer(), nullable=True),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('clase_detectada', sa.String(length=80), nullable=False),
    sa.Column('confianza', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('tracking_id_externo', sa.String(length=120), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keypoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_deteccion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_camara'], ['camaras.id_camara'], ),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos_seguridad.id_evento'], ),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelos_ia.id_modelo'], ),
    sa.PrimaryKeyConstraint('id_deteccion')
    )
    op.create_index('idx_detecciones_camara_ubicacion', 'detecciones_camara', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_table('rutas_calculadas',
    sa.Column('id_ruta', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('id_track', sa.BigInteger(), nullable=True),
    sa.Column('id_punto_turistico', sa.Integer(), nullable=True),
    sa.Column('tipo_ruta', sa.String(length=80), nullable=False),
    sa.Column('origen', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('destino', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('score_riesgo', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_confianza', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('distancia_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('duracion_estimada_seg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('algoritmo', sa.String(length=120), nullable=True),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos_seguridad.id_evento'], ),
    sa.ForeignKeyConstraint(['id_punto_turistico'], ['puntos_turisticos.id_punto_turistico'], ),
    sa.ForeignKeyConstraint(['id_track'], ['track_objetos.id_track'], ),
    sa.PrimaryKeyConstraint('id_ruta')
    )
    op.create_index('idx_rutas_calculadas_destino', 'rutas_calculadas', ['destino'], unique=False, postgresql_using='gist')
    op.create_index('idx_rutas_calculadas_geom', 'rutas_calculadas', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_rutas_calculadas_origen', 'rutas_calculadas', ['origen'], unique=False, postgresql_using='gist')
    op.create_table('comportamientos_detectados',
    sa.Column('id_comportamiento', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_deteccion', sa.BigInteger(), nullable=False),
    sa.Column('id_modelo', sa.Integer(), nullable=True),
    sa.Column('tipo_comportamiento', sa.String(length=100), nullable=False),
    sa.Column('confianza', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('severidad', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_deteccion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_deteccion'], ['detecciones_camara.id_deteccion'], ),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelos_ia.id_modelo'], ),
    sa.PrimaryKeyConstraint('id_comportamiento')
    )
    op.create_table('evento_detecciones',
    sa.Column('id_evento_deteccion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_deteccion', sa.BigInteger(), nullable=False),
    sa.Column('relacion', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_deteccion'], ['detecciones_camara.id_deteccion'], ),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos_seguridad.id_evento'], ),
    sa.PrimaryKeyConstraint('id_evento_deteccion')
    )
    op.create_table('evidencias_media',
    sa.Column('id_evidencia', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('id_deteccion', sa.BigInteger(), nullable=True),
    sa.Column('tipo_media', sa.String(length=50), nullable=False),
    sa.Column('path_archivo', sa.Text(), nullable=True),
    sa.Column('url_archivo', sa.Text(), nullable=True),
    sa.Column('fecha_captura', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_deteccion'], ['detecciones_camara.id_deteccion'], ),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos_seguridad.id_evento'], ),
    sa.PrimaryKeyConstraint('id_evidencia')
    )
    op.create_table('ruta_puntos_control',
    sa.Column('id_punto_control', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_ruta', sa.BigInteger(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('tipo_punto', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas_calculadas.id_ruta'], ),
    sa.PrimaryKeyConstraint('id_punto_control')
    )
    op.create_index('idx_ruta_puntos_control_ubicacion', 'ruta_puntos_control', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_table('rutas_segmentos',
    sa.Column('id_segmento', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_ruta', sa.BigInteger(), nullable=False),
    sa.Column('id_edge', sa.BigInteger(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('distancia_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('riesgo_segmento', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('costo_segmento', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['id_edge'], ['calles_edges.id_edge'], ),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas_calculadas.id_ruta'], ),
    sa.PrimaryKeyConstraint('id_segmento')
    )
    op.create_index('idx_rutas_segmentos_geom', 'rutas_segmentos', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('track_observaciones',
    sa.Column('id_observacion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_track', sa.BigInteger(), nullable=False),
    sa.Column('id_deteccion', sa.BigInteger(), nullable=True),
    sa.Column('id_camara', sa.Integer(), nullable=True),
    sa.Column('fecha_observacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('velocidad_estimada_m_s', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('direccion_grados', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id_camara'], ['camaras.id_camara'], ),
    sa.ForeignKeyConstraint(['id_deteccion'], ['detecciones_camara.id_deteccion'], ),
    sa.ForeignKeyConstraint(['id_track'], ['track_objetos.id_track'], ),
    sa.PrimaryKeyConstraint('id_observacion')
    )
    op.create_index('idx_track_observaciones_ubicacion', 'track_observaciones', ['ubicacion'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_track_observaciones_ubicacion', table_name='track_observaciones', postgresql_using='gist')
    op.drop_table('track_observaciones')
    op.drop_index('idx_rutas_segmentos_geom', table_name='rutas_segmentos', postgresql_using='gist')
    op.drop_table('rutas_segmentos')
    op.drop_index('idx_ruta_puntos_control_ubicacion', table_name='ruta_puntos_control', postgresql_using='gist')
    op.drop_table('ruta_puntos_control')
    op.drop_table('evidencias_media')
    op.drop_table('evento_detecciones')
    op.drop_table('comportamientos_detectados')
    op.drop_index('idx_rutas_calculadas_origen', table_name='rutas_calculadas', postgresql_using='gist')
    op.drop_index('idx_rutas_calculadas_geom', table_name='rutas_calculadas', postgresql_using='gist')
    op.drop_index('idx_rutas_calculadas_destino', table_name='rutas_calculadas', postgresql_using='gist')
    op.drop_table('rutas_calculadas')
    op.drop_index('idx_detecciones_camara_ubicacion', table_name='detecciones_camara', postgresql_using='gist')
    op.drop_table('detecciones_camara')
    op.drop_table('camara_streams')
    op.drop_table('camara_estados')
    op.drop_index('idx_camara_cobertura_geom', table_name='camara_cobertura', postgresql_using='gist')
    op.drop_table('camara_cobertura')
    op.drop_table('alertas_seguridad')
    op.drop_index('idx_reportes_seguridad_ubicacion', table_name='reportes_seguridad', postgresql_using='gist')
    op.drop_table('reportes_seguridad')
    op.drop_table('historial_riesgo_zona')
    op.drop_table('factores_riesgo_zona')
    op.drop_index('idx_eventos_seguridad_ubicacion', table_name='eventos_seguridad', postgresql_using='gist')
    op.drop_table('eventos_seguridad')
    op.drop_index('idx_camaras_ubicacion', table_name='camaras', postgresql_using='gist')
    op.drop_table('camaras')
    op.drop_index('idx_calles_edges_geom', table_name='calles_edges', postgresql_using='gist')
    op.drop_table('calles_edges')
    op.drop_index('idx_zonas_geom', table_name='zonas', postgresql_using='gist')
    op.drop_index('idx_zonas_centro', table_name='zonas', postgresql_using='gist')
    op.drop_table('zonas')
    op.drop_index('idx_puntos_turisticos_ubicacion', table_name='puntos_turisticos', postgresql_using='gist')
    op.drop_table('puntos_turisticos')
    op.drop_table('ejecuciones_modelo')
    op.drop_index('idx_track_objetos_ultima_ubicacion', table_name='track_objetos', postgresql_using='gist')
    op.drop_table('track_objetos')
    op.drop_index('idx_municipios_geom', table_name='municipios', postgresql_using='gist')
    op.drop_table('municipios')
    op.drop_table('modelos_ia')
    op.drop_table('fuentes_datos')
    op.drop_index('idx_calles_nodes_geom', table_name='calles_nodes', postgresql_using='gist')
    op.drop_table('calles_nodes')
    # ### end Alembic commands ###
